import * as announcement from './entities/announcement';
import * as app from './entities/app';
import * as blocking from './entities/blocking';
import * as created_note from './entities/createdNote';
import * as emoji from './entities/emoji';
import * as favorite from './entities/favorite';
import * as field from './entities/field';
import * as file from './entities/file';
import * as follow from './entities/follow';
import * as follow_request from './entities/followRequest';
import * as hashtag from './entities/hashtag';
import * as instance from './entities/instance';
import * as list from './entities/list';
import * as meta from './entities/meta';
import * as mute from './entities/mute';
import * as note from './entities/note';
import * as notification from './entities/notification';
import * as poll from './entities/poll';
import * as reaction from './entities/reaction';
import * as relation from './entities/relation';
import * as session from './entities/session';
import * as stats from './entities/stats';
import * as user from './entities/user';
import * as user_detail from './entities/userDetail';
export declare namespace Entity {
    type Announcement = announcement.Announcement;
    type App = app.App;
    type Blocking = blocking.Blocking;
    type CreatedNote = created_note.CreatedNote;
    type Emoji = emoji.Emoji;
    type Favorite = favorite.Favorite;
    type Field = field.Field;
    type File = file.File;
    type Follow = follow.Follow;
    type FollowRequest = follow_request.FollowRequest;
    type Hashtag = hashtag.Hashtag;
    type Instance = instance.Instance;
    type AccountEmoji = instance.AccountEmoji;
    type List = list.List;
    type Meta = meta.Meta;
    type Mute = mute.Mute;
    type Note = note.Note;
    type NoteVisibility = note.NoteVisibility;
    type Notification = notification.Notification;
    type NotificationType = notification.NotificationType;
    type Poll = poll.Poll;
    type Choice = poll.Choice;
    type Reaction = reaction.Reaction;
    type Relation = relation.Relation;
    type Session = session.Session;
    type Stats = stats.Stats;
    type User = user.User;
    type UserDetail = user_detail.UserDetail;
    type UserDetailMe = user_detail.UserDetailMe;
}
export default Entity;
